# SPDX-License-Identifier: GPL-2.0-only
# Research candidate only. install.sh deliberately does not install this file.
# MBA91 warm preserve: omit sensor reset + calibration load from verify so a
# macOS-warmed 0x42 identity survives. Default daemon still resets + loads.
[Service]
ExecStart=
ExecStart=/opt/t2-touchid/.venv/bin/python /opt/t2-touchid/src/t2-fprintd.py --warm-verify
