#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only
set -u
PATH=/usr/bin:/bin
export PATH
ulimit -c 0

TOOL=/usr/local/sbin/t2-aks-tool
READY_HELPER=/usr/local/sbin/t2-pam-fingerprint-ready
STATE_FILE=/run/t2-touchid/keybag.env
READY_FILE=/run/t2-touchid/keybags-unlocked
CONFIG_FILE=/etc/t2-touchid.conf

# This hook is intentionally a no-op for other users or unavailable state.
[[ -r $CONFIG_FILE && -r $STATE_FILE && -x $TOOL ]] || exit 0
[[ ${PAM_SERVICE:-} == sudo ]] || exit 0
configured_user=$(sed -n 's/^T2_TOUCHID_USER=\([A-Za-z0-9_.-][A-Za-z0-9_.-]*\)$/\1/p' "$CONFIG_FILE")
[[ -n $configured_user && ${PAM_USER:-} == "$configured_user" ]] || exit 0
[[ -x $READY_HELPER ]] && "$READY_HELPER" && exit 0

# The file is generated by t2-keybag-load and is root-only. Validate every
# value rather than sourcing it.
rm -f -- "$READY_FILE"
snapshot=$(mktemp "${READY_FILE}.XXXXXX") || exit 0
trap 'rm -f -- "$snapshot"' EXIT
install -o root -g root -m 0600 "$STATE_FILE" "$snapshot" || exit 0
session=$(sed -n 's/^T2_KEYBAG_SESSION=\([0-9][0-9]*\)$/\1/p' "$snapshot")
handle=$(sed -n 's/^T2_KEYBAG_HANDLE=\(-\{0,1\}[0-9][0-9]*\)$/\1/p' "$snapshot")
special=$(sed -n 's/^T2_KEYBAG_SPECIAL=\(-\{0,1\}[0-9][0-9]*\)$/\1/p' "$snapshot")
[[ -n $session && -n $handle && -n $special ]] || exit 0

# Linux authentication has already succeeded. Ask separately for the macOS
# password so the two accounts do not need to share a credential.
if "$TOOL" unlock-keybags "$session" "$handle" "$special" \
    >/dev/null 2>&1 && cmp -s -- "$snapshot" "$STATE_FILE"; then
  mv -f -- "$snapshot" "$READY_FILE"
  trap - EXIT
  systemctl try-restart --no-block fprintd.service || true
  logger --priority authpriv.info --tag t2-pam-unlock 'keybags unlocked from PAM password authentication'
else
  logger --priority authpriv.warning --tag t2-pam-unlock 'keybag unlock attempt failed closed'
fi
exit 0
