# SPDX-License-Identifier: GPL-2.0-only
# MBA91 (MacBookAir9,1) has no Linux-local Catacomb and no canonical
# per-finger labels: verification runs through the token-free opcode-4
# match behind a single compatibility alias. This drop-in selects the
# verify-only MBA91 daemon instead of the default broker. Installed by
# install.sh only when T2_TOUCHID_MBA91_WARM_SEP=1.
[Service]
ExecStart=
ExecStart=/opt/t2-touchid/.venv/bin/python /opt/t2-touchid/src/t2-fprintd-mba91.py --match-seconds 30
